### ISSUE TITLE
Maya 2023 error

### ISSUE THREAD

**Issue by fluffyamao** [ScriptorBob/stream-flow#1]
Plugin Version : 1.0.01-Beta
Maya Version : 2023.2
Maya Language : English
System : Windows 10 21H2
- - - - - - - - - - - - - - - - - -
I installed it, then ran the python command, and got an error.

streamflow_fn_()
# Error: NameError: file <maya console> line 1: name 'streamflow_fn_' is not defined

**Comment by ScriptorBob** [comment]
Please provide a snapshot of Maya's console after startup. If it is not available. go to Windows > Output Window.
Do check if pymel is installed, as it is a library this plug-in uses. If it is not installed, here is an [installation guide](https://knowledge.autodesk.com/support/maya/learn-explore/caas/CloudHelp/cloudhelp/2023/ENU/Maya-Scripting/files/GUID-2AA5EFCE-53B1-46A0-8E43-4CD0B2C72FB4-htm.html)
I haven't tested the plug-in on Maya 2023 yet, but it is a common issue in Maya 2022.

**Comment by ScriptorBob** [comment]
Newer versions of Maya do not come with PyMel installed, and you need to manually install it now. The error "name 'streamflow_fn_' is not defined" signifies that the plug-in can not start at Maya startup, and most of the time it is because the PyMel library is not available.
