### ISSUE TITLE
Very good plug-in. Will it have a 2023 plan?

### ISSUE THREAD

**Issue by MrLiu92** [ScriptorBob/stream-flow#2]
We look forward to using it in collaboration with the later version of Ctrl+F search

**Comment by ScriptorBob** [comment]
I haven't tested the plug-in on Maya 2023 yet, but it works on Maya 2022, which is closer to 2023 then it's predecessors.

Maya 2022 and 2023 sometimes get shipped without the pymel library, without which this plug-in won't work. If it is not installed, here is an [installation guide](https://knowledge.autodesk.com/support/maya/learn-explore/caas/CloudHelp/cloudhelp/2023/ENU/Maya-Scripting/files/GUID-2AA5EFCE-53B1-46A0-8E43-4CD0B2C72FB4-htm.html).

**Comment by MrLiu92** [comment]
Ok, thank you very much

**Comment by ScriptorBob** [comment]
It now fully supports 2023, and is working but untested on 2024
