### ISSUE TITLE
How to delete Autosave popup after uninstalling

### ISSUE THREAD

**Issue by mistywidow** [ScriptorBob/stream-flow#4]
Hello,
My maya 2023 got freeze many times so I had to uninstall it. 
I did uninstall it as the guide.
But Still Autosave asking "Autosave is disabled. Would you like to save now?" popup, how do I delete it?

**Comment by ScriptorBob** [comment]
I apologize for the late response.
Pleas read [Here](https://github.com/ScriptorBob/stream-flow/blob/main/README.md#uninstallation-guide) on how to uninstall the plugin.

Key notes:
Open the file userSetup.py from: \Users\<USER>\Documents\maya\<MayaVersion>\prefs\scripts
Remove these lines of code from there:

         """MMGA IMPORT"""
         import os
         import maya
         import MMGA
        
         with open(os.path.splitext(MMGA.__file__)[0] + ".py") as fh:
             exec (fh.read())
        
         maya.cmds.evalDeferred("streamflow_fn_()",lp=1)
         """MMGA IMPORT"""

Other options:
1. You can delete the whole userSetup.py  file from that location.
If you haven't modified this file yourself, it is safe to do so, it contains things to create on Maya startup, and is usually empty
3. You can also delete the whole prefs folder, maya will recreate it automatically:
: \Users\<USER>\Documents\maya\<MayaVersion>\prefs
Please note that this option will reset maya to factory settings. - Settings, shelves, ui layout, all will be reset to factory settings.

Overall, clearing the file userSetup.py will stop the plugin from being called.
Once you delete the file, or the required lines of code contained with in it, all other files that the plugin uses become insubstantial.

**Comment by ScriptorBob** [comment]
If  you follow these steps the problem should not occur any more. Now there is an update which support 2023 fully. I will mark this issue as closed now since I received no response.
